### ISSUE TITLE
nvcc build failure of podio generated code

### ISSUE THREAD

**Issue by vvolkl** [key4hep/k4Clue#34]
The changes introduced  in https://github.com/AIDASoft/podio/pull/295 are breaking the builds with nvcc (https://gitlab.cern.ch/key4hep/k4Clue/-/jobs/24580083). Not sure if the edm4hep dependent part can be separated and built with gcc or this needs to be fixed to compile with nvcc.

This line: 
https://github.com/AIDASoft/podio/pull/295/files#diff-c203d3c7391344595ed7e96696327c7620f35eb072145e7698f2fb623ab17445R151

**Comment by tmadlener** [comment]
Some follow up on the discussion during the meeting today:
- The culprit seems to be the direct initialization of the `unique_ptr`. This could in principle be fixed in the generated code. I would have to check whether this is possible with reasonable effort.
- We discussed the prospect of not building this with nvcc, but I now realized that this is in fact part of the core EDM4hep library, so I am not entirely sure this can be easily split off into a separate part.
